version: '3.8'
services:
  java-app:
    container_name: java-backend-compose
    image: "openjdk:17-jdk-slim"
    restart: always
    working_dir: /app
    volumes:
      - "/Users/vadim/Downloads/Java/Java practice/currency-exchange-service/target/cd:/app/app.jar"
    environment:
      - "ENVIRONMENT=production"
      - "PORT=9090"
    ports:
      - "9090:9090"
    command: [ "java", "-jar", "app.jar" ]